# Generated by Django 4.0.4 on 2022-05-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0002_alter_familiares_fecha_nac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiares',
            name='fecha_nac',
            field=models.DateTimeField(),
        ),
    ]
