# Generated by Django 4.0.4 on 2022-05-27 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0003_alter_familiares_fecha_nac'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='familiares',
            new_name='Familia',
        ),
    ]
